
name: "Dethrace reccmp"
description: "A GitHub Action that runs inside a Docker container"
author: "Your Name"

inputs:
  cmake-flags:
    description: "An example input"
    required: true
  command:
    description: "An example input"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
